### ISSUE TITLE
"Sensor in the air" bug

### ISSUE THREAD

**Issue by pavtiger** [physarumAdv/Fluffy-Physarum#2]
When a particle comes close to the edge of the polyhedron face, being still on it, the sensor must be already positioned on the contacting face. However, this math mistake makes the sensor "flying in the air". It brings us to the mistakes in particle behavior when particles don't jump to the next face.

**Comment by kolayne** [comment]
Unfortunately, we decided to rewrite the project from scratch, so we are not working on this anymore. The new version is at https://github.com/physarumAdv/mind-s_crawl
